### ISSUE TITLE
inputs.json instead of input.json?

### ISSUE THREAD

**Issue by AlexDo1** [hydrocode-de/json2args#13]
Refering to the [tool-specs](https://vforwater.github.io/tool-specs/tool/) it should be `inputs.json`, but json2args is looking for `input.json`.

Two possible ways:
* change `input.json` -> `inputs.json`  here in json2args for Python
* change `inputs.json` -> `input.json` in json2aRgs and tool specs

**Comment by mmaelicke** [comment]
I choose the thrird option:

* we communicate `inputs.json` everywhere and **add** that as a option to json2args for Python, but secretly still supporting `input.json` so that we don't break everything right now. 

We can than later deprecate `input.json` and remove it if we want to

**Comment by AlexDo1** [comment]
> we communicate inputs.json everywhere and add that as a option to json2args for Python, but secretly still supporting input.json so that we don't break everything right now.
We can than later deprecate input.json and remove it if we want to

Sorry, I got that wrong in my first comment in this issue, here is the clarification:
* tool-specs: `input.json`
* json2aRgs: `input.json`
* json2args: `inputs.json`

So following the tool-specs, we communicate `input.json` everywhere and make json2args also support that.

I think that we could test here if `PARAM_FILE` is `inputs.json` and check if it exists, if it does not exist we could check if `input.json` exists and return it if it exists:
https://github.com/hydrocode-de/json2args/blob/e449fba29968323c4a07c2aeab4afea4011c12d7/json2args/util.py#L10-L14

Or we could do the same here:
https://github.com/hydrocode-de/json2args/blob/e449fba29968323c4a07c2aeab4afea4011c12d7/json2args/util.py#L23-L26

**Comment by mmaelicke** [comment]
You want me to take care of that myself? You can either assign me or yourself to implement the changes
